---
title: "Econ570-G5-Final"
output:
  html_document: default
  pdf_document: default
date: "2023-05-06"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#load the dataset
setwd("/Users/yuqipang/Documents/570 data")
data= read.csv("birpanel.csv")
```
```{r}
#see the summary of data
summary(data)
```
```{r}
#clean the data, convert 99(unknown) in cigar into average value.
data$cigar[data$cigar == 99] <- mean(data$cigar[data$cigar != 99 & data$cigar != 0], na.rm = TRUE)
```
```{r}
# generate and plot correlation matrix
library(ggcorrplot)
cor_matrix <- cor(data)
cor_matrix
ggcorrplot(cor_matrix,type=c("full"), tl.cex=7)

```
```{r}
#choose control variables based on correlation matrix
control_vars <- c("dmage", "nlbnl", "gestat", "male", "married", "hsgrad", "somecoll", "collgrad", "black", "adeqcode2", "adeqcode3", "novisit", "pretri2", "pretri3")
# dmeduc is not chosen. Cause hsgrad, somecoll, collgrad are generated by demeduc. agesq is also not used, since it has abnormal distribution and high variance, given we already had age as control varible.
```
#for each method, run twice using different treatment(smoke or cigar), except PSM


#Method1:Baseline regression(multiple linear regression)
```{r}
#Baseline model using smoke as treatment
baseline_smoke <- lm(dbirwt ~ smoke + dmage + nlbnl + gestat + male + married + hsgrad + somecoll + collgrad + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = data)
summary(baseline_smoke)

coef_smoke <- summary(baseline_smoke)$coefficients["smoke", ]
tvalue_smoke <- coef_smoke["t value"]
pvalue_smoke <- coef_smoke["Pr(>|t|)"]

cat("Coefficient for smoke:", coef_smoke[1], "\n")
cat("t-value for smoke:", tvalue_smoke, "\n")
cat("p-value for smoke:", pvalue_smoke, "\n")

```

```{r}
#Baseline model using cigar as treatment
baseline_cigar <- lm(dbirwt ~ cigar + dmage + nlbnl + gestat + male + married + hsgrad + somecoll + collgrad + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = data)
summary(baseline_cigar)

coef_cigar <- summary(baseline_cigar)$coefficients["cigar", ]
tvalue_cigar <- coef_cigar["t value"]
pvalue_cigar <- coef_cigar["Pr(>|t|)"]

# Print the results
cat("Coefficient for cigar:", coef_cigar[1], "\n")
cat("t-value for cigar:", tvalue_cigar, "\n")
cat("p-value for cigar:", pvalue_cigar, "\n")

```


#Method2:Fixed effects model: regression on difference
```{r}
# generate difference between two pregnancy for variables
library(dplyr)
diff = data %>%
  group_by(momid3) %>%
  mutate(idx = idx - lag(idx)) %>%
  mutate(stateres = stateres - lag(stateres)) %>%
  mutate(dmage = dmage - lag(dmage)) %>%
  mutate(dmeduc = dmeduc - lag(dmeduc)) %>%
  mutate(mplbir = mplbir - lag(mplbir)) %>%
  mutate(nlbnl = nlbnl - lag(nlbnl)) %>%
  mutate(gestat = gestat - lag(gestat)) %>%
  mutate(dbirwt = dbirwt - lag(dbirwt)) %>%
  mutate(cigar = cigar - lag(cigar)) %>%
  mutate(smoke = smoke - lag(smoke)) %>%
  mutate(male = male - lag(male)) %>%
  mutate(year = year - lag(year)) %>%
  mutate(married = married - lag(married)) %>%
  mutate(hsgrad = hsgrad - lag(hsgrad)) %>%
  mutate(somecoll = somecoll - lag(somecoll)) %>%
  mutate(collgrad = collgrad - lag(collgrad)) %>%
  mutate(agesq = agesq - lag(agesq)) %>%
  mutate(black = black - lag(black)) %>%
  mutate(adeqcode2 = adeqcode2 - lag(adeqcode2)) %>%
  mutate(adeqcode3 = adeqcode3 - lag(adeqcode3)) %>%
  mutate(novisit = novisit - lag(novisit)) %>%
  mutate(pretri2 = pretri2 - lag(pretri2)) %>%
  mutate(pretri3 = pretri3 - lag(pretri3)) %>%
  slice_tail(n = 1)

summary(diff)
```

```{r}
# regression on difference. Treatment=smoke
diff_smoke = lm(dbirwt ~ smoke + dmage + gestat + male  + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = diff)
summary(diff_smoke)

coef_smoke <- summary(diff_smoke)$coefficients["smoke", ]
tvalue_smoke <- coef_smoke["t value"]
pvalue_smoke <- coef_smoke["Pr(>|t|)"]

cat("Coefficient for smoke:", coef_smoke[1], "\n")
cat("t-value for smoke:", tvalue_smoke, "\n")
cat("p-value for smoke:", pvalue_smoke, "\n")
```

```{r}
# regression on difference. Treatment=smoke
diff_cigar = lm(dbirwt ~ cigar + dmage + gestat + male  + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = diff)
summary(diff_cigar)

coef_cigar <- summary(diff_cigar)$coefficients["cigar", ]
tvalue_cigar <- coef_smoke["t value"]
pvalue_cigar <- coef_smoke["Pr(>|t|)"]

cat("Coefficient for cigar:", coef_cigar[1], "\n")
cat("t-value for cigar:", tvalue_cigar, "\n")
cat("p-value for cigar:", pvalue_cigar, "\n")
```


#Method3:PSM Propensity Score Matching 
```{r}
library(dplyr)
library(MatchIt)
vars_to_match <- c("dmage", "nlbnl", "gestat", "male", "married", "hsgrad", "somecoll", "collgrad", "black", "adeqcode2", "adeqcode3", "novisit", "pretri2", "pretri3")
data_match <- data %>% dplyr::select(dbirwt, smoke, one_of(vars_to_match))
m.out <- matchit(smoke ~ dmage + nlbnl + gestat + male + married + hsgrad + somecoll + collgrad + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = data_match, method = "nearest")
matched_data <- match.data(m.out)
PSM_smoke<- lm(dbirwt ~ smoke, data = matched_data)
summary(PSM_smoke)
```


#Method4:Instrument variable: dmeduc
```{r}
# Treatment=smoke
library(AER)
iv_smoke <- ivreg(dbirwt ~ smoke + dmage + nlbnl + gestat + male + married + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3 | dmeduc+ dmage + nlbnl + gestat + male + married + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = data)

summary(iv_smoke, vcov = sandwich, diagnostics = TRUE)
```

```{r}
# Treatment=cigar
iv_cigar <- ivreg(dbirwt ~ cigar + dmage + nlbnl + gestat + male + married + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3 | dmeduc+ dmage + nlbnl + gestat + male + married + black + adeqcode2 + adeqcode3 + novisit + pretri2 + pretri3, data = data)

summary(iv_cigar, vcov = sandwich, diagnostics = TRUE)
```





